{% set name = "redframes" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redframes-{{ version }}.tar.gz
  sha256: a340a7b9e1b09b5e32967e67fecef5b0e7026a9c0c379ab8ec872f0ba2d7b5a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pandas >=1.5,<2.0
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - redframes
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - matplotlib-base
    - pip
    - pytest
    - scikit-learn
    - python {{ python_min }}

about:
  home: https://github.com/maxhumber/redframes
  summary: General Purpose Data Manipulation Library
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
